CREATE TABLE IF NOT EXISTS user_koibito_stats (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  koibito_id INTEGER,
  messages_sent INTEGER DEFAULT 0,
  messages_received INTEGER DEFAULT 0,
  chat_minutes INTEGER DEFAULT 0,
  long_sessions INTEGER DEFAULT 0,
  late_night_sessions INTEGER DEFAULT 0,
  meaningful_messages INTEGER DEFAULT 0,
  voice_sessions INTEGER DEFAULT 0,
  voice_minutes INTEGER DEFAULT 0,
  comfort_count INTEGER DEFAULT 0,
  vent_count INTEGER DEFAULT 0,
  flirt_count INTEGER DEFAULT 0,
  games_played INTEGER DEFAULT 0,
  games_won INTEGER DEFAULT 0,
  games_lost INTEGER DEFAULT 0,
  rp_sessions INTEGER DEFAULT 0,
  moments_posted INTEGER DEFAULT 0,
  koibito_opens INTEGER DEFAULT 0,
  quick_returns INTEGER DEFAULT 0,
  night_activity_count INTEGER DEFAULT 0,
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, koibito_id)
);